// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'zh'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * O​b​s​i​d​i​a​n​ ​插​件​入​门
	 */
	'obsidian-plugin-starter': string
}

export type TranslationFunctions = {
	/**
	 * Obsidian 插件入门
	 */
	'obsidian-plugin-starter': () => LocalizedString
}

export type Formatters = {}
